### PR TITLE
Ben sizes

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Comment by uditvira** [comment]
lgtm but I think the font weight can be reduced or font colour can be lightened because it still looks slightly heavy

**Comment by bennlich** [comment]
Are you sure about this? I'm pretty sure you reverted the header to the same size it was before.

**Comment by bennlich** [comment]
I like this body font size and line spacing for articles.

**Comment by bennlich** [comment]
@benhylau I took some of your changes and reverted some others. I made the desktop header slightly bigger, but not as big as you had made it.

**Comment by bennlich** [comment]
I like the typography of the piece pages. I think the typography of the home page and TOC could be improved, but im not sure how yet.

**Comment by benhylau** [comment]
Mine:

Screen Shot 2021-02-22 at 11 00 10 AM

Current:

Screen Shot 2021-02-22 at 11 00 01 AM

I definitely like mine much better :)

**Comment by benhylau** [comment]
Mine:

Screen Shot 2021-02-22 at 11 10 49 AM

Current:

Screen Shot 2021-02-22 at 11 10 55 AM

**Pull request merged**
